### ISSUE TITLE
Doucmentation

### ISSUE THREAD

**Issue by benpeckham04** [knicola/tdameritradejs#13]
Where can I find documentation for this library?

**Comment by knicola** [comment]
documentation is still work in progress. for now, you can have a look at the [typescript definitions](https://github.com/knicola/tdameritradejs/blob/master/types/tdAmeritrade.d.ts) for the api client to see what you can do with it. for the data streamer you will have to go through the [code](https://github.com/knicola/tdameritradejs/blob/master/src/tdStreamer.js)
