### ISSUE TITLE
Returned data is the HTTP response vs the body

### ISSUE THREAD

**Issue by oransel** [knicola/tdameritradejs#2]
Good job with this module.

There is an issue with the HTTP function returns. They return the complete HTTP response vs the body and the other functions expect the operate with the body.

For example;
`const accounts = await api.getAccounts()`
`api.getOrders(accounts[0].accountId).then( ... )`

`accounts` cannot be used like it is shown in the next line. It needs to be `accounts.data[0]...`.

This is also the same issue with `userPrincipals`. It either needs to be returned with properties containing the body data, or the streamer functions need to reference the data property.

**Comment by knicola** [comment]
Thank you! :)

I'll have to update the readme file. It's much better to return the HTTP response than just the body since it gives access to the status code, headers, etc.

**Comment by knicola** [comment]
I've reconsidered the idea of returning the full response. It's much simpler and much cleaner to return the data directly. On the other hand, there's cases where an endpoint will return a successful HTTP status code, but with a twist. For example, [Get Accounts](https://developer.tdameritrade.com/account-access/apis/get/accounts-0) might return a `207` code with "partial" data. To some, this might be an issue and having access to the status code will be preferred.

So instead, I've added an option to control how the HTTP response is returned and also exposed the axios instance to allow the user to add interceptors.

**Comment by oransel** [comment]
Sounds good.

In the meanwhile, I extensively changed the architecture to handle OAuth and refresh token management. All HTTP responses are hidden from the user, mostly for my use case. 

I also added CHART_HISTORY_FUTURES. It took a while to get this working. cuid module doesn't work for this one.

Let me know if I can help with anything. A pull request will change it all and I don't think this is the direction you want to take this module, since it is only for my use case.

**Comment by knicola** [comment]
I'd love to see what you came up with! Maybe I can borrow an idea or two :)

> I also added CHART_HISTORY_FUTURES. It took a while to get this working. cuid module doesn't work for this one.

Does this service require `requestid` to be an integer?

> Let me know if I can help with anything.

Will do! There's a couple of things I might need help with, but I'll have to revisit my notes first.
