### ISSUE TITLE
Scripts cannot run when installed as a node module

### ISSUE THREAD

**Issue by oransel** [knicola/tdameritradejs#3]
`scripts/authorize.js` is not structured to run when installed as a node module to be integrated into another app. 

Certs are expected to be in the root of the module. This is not ideal for an application.

**Comment by oransel** [comment]
It will be great if the oauth life cycle was built as a function/module instead of command line apps.

**Comment by knicola** [comment]
The scripts were only intended to be used for the development of this module, but I can perhaps look into the possibility of writing a separate auth module.

**Comment by oransel** [comment]
It will be a nice addition to have the auth handled for the user of the module. Almost all the work is there already. Mostly, the environment variables and cert location can be passed in as function parameters.

**Comment by knicola** [comment]
The scripts have been removed. Instead 2 new methods will be added to make oauth2 authorization much easier.

* `TDAmeritrade.authorize(): Promise` to bootstrap a local web server for oauth2 authorization. Will request access token and update config if authorization is successful.
* `TDAmeritrade.login(): Promise` to automatically authorize or refresh the access token depending on whether the access and/or refresh token exist and are not expired.
