### ISSUE TITLE
How to get Futures quotes faster than 1 minue

### ISSUE THREAD

**Issue by oransel** [knicola/tdameritradejs#4]
This could be a TD API limitation. Is there a way to pass frequency into the streamer for the futures contracts? Right now, it updates every minute. Can it be every 5 seconds, etc?

**Comment by knicola** [comment]
Though not documented, this seems to be an API limitation. I've even tried setting the qos level to 500ms, but has zero effect on chart data.

**Comment by oransel** [comment]
Are we supposed to use LEVELTWO_FUTURES?

**Comment by knicola** [comment]
I believe `TIMESALE_FUTURES` is a better option for that.

**Comment by oransel** [comment]
Probably correct. It seems like the chart sub is only one minute.
Then, it seems like the user app needs to calculate OHLCV with the TIMESALE_FUTURES data for that minute.

From the docs:

> 8.0 CHART
> Chart provides  streaming one minute OHLCV (Open/High/Low/Close/Volume) for a one minute period .
> The one minute bar falls on the 0 second slot (ie. 9:30:00) and includes data from 0 second to 59 seconds.
> For example, a 9:30 bar includes data from 9:30:00 through 9:30:59.
