### ISSUE TITLE
Self signed cert generation update

### ISSUE THREAD

**Issue by oransel** [knicola/tdameritradejs#5]
Suggested Openssl command in the readme didn't yield the expected results on macOS and Chrome browser.

This worked well:
`openssl req -x509 -out selfsigned.crt -keyout selfsigned.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")`

**Comment by knicola** [comment]
Thank you for sharing! I don't have a macOS to confirm this but if it behaves the same under linux and windows it might be the better option.

**Comment by oransel** [comment]
Confirmed for Linux.

**Comment by knicola** [comment]
updating readme to include both `openssl` commands.
