### ISSUE TITLE
Add support for CHART_HISTORY_FUTURES

### ISSUE THREAD

**Issue by knicola** [knicola/tdameritradejs#7]
https://developer.tdameritrade.com/content/streaming-data#_Toc504640593

note: connection drops after sending the request to the server without any warning message.

**Comment by knicola** [comment]
The `requestid`, generated with the help of the `cuid` node module, might be causing the streaming server to drop the connection.

https://github.com/knicola/tdameritradejs/issues/2#issuecomment-670303032

**Comment by oransel** [comment]
`requestid` needs to be integer

**Comment by knicola** [comment]
it also has a max number limitation, but it's hard to figure out exactly what the max number is.
I would hate having to keep a state in this module for the `requestid` and unfortunately, since the max number is not documented, number generation is out of the question.

a possible solution would be to set a static `requestid` for `CHART_HISTORY_FUTURES`, so something like this would do:
```js
   getChartHistoryFutures(symbols, options) {
        return this.sendRequest({
            requestid: 123, // overwriting cuid generation
            service: SERVICES.CHART_HISTORY_FUTURES,
            command: COMMANDS.GET,
            parameters: Object.assign({}, options, {
                symbol: [].concat(symbols).join(',').toUpperCase()
            })
        })
    } // getChartHistoryFutures()
```

**Comment by knicola** [comment]
settled for a randomized `requestid` between 0 and 2,000,000,000 only for `.getChartHistoryFutures()`. anything greater than that can potentially fail.

will have to revisit `requestid` generation for all services later on. at this point I can't even think of what the real value for it is.

**Comment by oransel** [comment]
uint32 can hold 4,294,967,295
int32 in absolute value is 2,147,483,647.5

Pretty close to the number you are referencing. I wonder if the internal systems at TDA is converting the requestId to int32 and expect it to be only positive.
