### ISSUE TITLE
Add auth methods

### ISSUE THREAD

**Issue by knicola** [knicola/tdameritradejs#8]
Need to add methods for oauth authentication and token refresh:
* `.authenticate()` to request an access token
* `.refreshToken()` to request a new access token

**Comment by oransel** [comment]
Let me know how I can share what I have done to re-org for my specific use.

**Comment by knicola** [comment]
> Let me know how I can share what I have done to re-org for my specific use.

you can create a new repo and push the code. it can be a private one if you so choose to and add me to it
